services:
  server:
    container_name: toadoverlay
    build:
      context: https://github.com/darkstormgames/ToadOverlay.git#celebration_update
    volumes:
      - type: bind
        source: /usr/src/app/app_data
        target: /var/toadoverlay/app_data
      - type: bind
        source: /run/secrets
        target: /var/secrets
    environment:
      NODE_ENV: production
      PREFIX: _
      LOGLEVEL: DEBUG
      ENVIRONMENT: PRODUCTION
      ADMIN_ID: 329925485796524053
      CLIENT_TOKEN: /run/secrets/token
      SQL_HOST: /run/secrets/host
      SQL_USER: /run/secrets/user
      SQL_PASS: /run/secrets/pass
      SQL_NAME: /run/secrets/name
    secrets:
      - token
      - host
      - user
      - pass
      - name
secrets:
  token:
    file: /run/secrets/token
  host:
    file: /run/secrets/host
  user:
    file: /run/secrets/user
  pass:
    file: /run/secrets/pass
  name:
    file: /run/secrets/name