services:
  maintenance:
    container_name: toadoverlay_maintenance
    build:
      context: https://github.com/darkstormgames/ToadOverlay.git#maintenance
    volumes:
      - /var/toadoverlay:/usr/src/app/app_data
      - /var/secrets:/run/secrets:ro
    environment:
      NODE_ENV: production
      PREFIX: _
      LOGLEVEL: DEBUG
      ENVIRONMENT: DEVELOPMENT
      CLIENT_TOKEN: /run/secrets/token
    secrets:
      - token
secrets:
  token:
    external: true